dist: xenial

language: python

python:
    - 3.7
    - 3.8

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry install
  - poetry add codecov

script:
  - pytest

after_success:
  - codecov
